### PR TITLE
change variable name in melted data frames for HTML and PDF outputs

### PR DESCRIPTION
**Pull request by matt-sd-watson**
I was receiving an error when attempting to export the PDF and HTML outputs, respectively. Some digging indicated that the melt function in `mitch_report()` `mitch_plots()` now produces a data frame with the default variable header "variable" in place of "Var2" in the source code. The modification of the variable header was necessary in order to export the required output files.

### CODE REVIEW

**Comment by markziemann** [comment]
Thanks for your contribution matt - I will give this code a try and hopefully pull it

**Comment by markziemann** [comment]
It seems that for yourself and other users, "varriable" looks like it's working. But for me, "Var2" works but not "variable".
Therefore I think the best way to solve this is to add a line of code to set the three column names:

```
colnames(sss_long) <- c("gene","contrast","value")
colnames(ss_long) <- c("gene","contrast","value")
```

Which I think will work for everyone.
I will do some further testing on this.

**Comment by matt-sd-watson** [comment]
Sounds like a good solution! If it works you can feel free to close this.

**Comment by markziemann** [comment]
I've made the changes and pushed to main. See: https://github.com/markziemann/mitch/commit/927e1da3f7c46af4a8dce3438fa2c91d0ddece46 
Thanks very much for raising this and helping to solve the problem!
This bugfix will likely be included in the next bioconductor release. For now, use the github version

**Pull request closed without merging**
